### ISSUE TITLE
评论框变宽了？

### ISSUE THREAD

**Issue by reverland** [forsigner/fexo#12]
更新后发现评论太宽了

现在
![screenshot from 2016-03-07 15 55 35](https://cloud.githubusercontent.com/assets/1418726/13563514/4684e178-e47d-11e5-958d-7c63cfbbb237.png)
之前
![screenshot from 2016-03-07 15 55 50](https://cloud.githubusercontent.com/assets/1418726/13563517/4978d920-e47d-11e5-8419-d5f08a991363.png)

**Comment by reverland** [comment]
似乎和cb2e83ac258d3182896ea938c1b032883bfcfdc8 有关

要不要把.content-post .CENTER和.fexo-comments .coments-posts用一个盒子放起来

**Comment by reverland** [comment]
。。。好吧，是我在markdown里把layout post写成posts了。。。

**Comment by forsigner** [comment]
我这边没问题啊

**Comment by forsigner** [comment]
ok.. 0_o

**Comment by reverland** [comment]
@forsigner 。。。这样layout一点都不能写错额

**Comment by forsigner** [comment]
哦哦 我看看哈
