### ISSUE TITLE
关于盒子按钮的讨论

### ISSUE THREAD

**Issue by HeroadZ** [forsigner/fexo#128]
1. 这个盒子按钮不是展开的，有些人不知道它能展开，所以没有看过里面的关于页面和搜索页面。这个盒子按钮能不能添加一个展开功能。
2. 在进入文章页面的时候，盒子按钮缩成了最上面的一个箭头，我感觉也很难被人注意到啊。是不是有更显眼的方式呢，探讨下。

**Comment by HeroadZ** [comment]
嗯，我是改成了“地图”。
盒子在文章页面时缩成了顶部箭头，虽然这对沉浸式阅读很好，但是对电脑小白来说的确不太友善，尤其是我没有开启文章末尾的prev和next按钮功能。
其实还是因为prev和next有点丑，不知大佬有没有想法换个样式。

**Comment by ykqmain** [comment]
@HeroadZ 

你可以设置默认在“新标签中打开”文章，每看一篇博客都是一个新标签，这样看完了之后，就可以直接关闭该页面，而不用再去找“盒子”进行下一步操作。

对于上一篇和下一篇，可以在`Blog/themes/fexo/layout/_partial/component/prev-net.ejs`里面自行修改，

```
<% if (theme.post.show_prev_next) {%>
  <div class="box-prev-next clearfix">
    <a class="<%- getStatus(page.next) %> pull-left" href="<%- url_for(getPrevUrl(page.next)) %>">
        <i class="icon icon-angle-left"></i>
    </a>
    <a class="<%- getStatus(page.prev) %> pull-right" href="<%- url_for(getPrevUrl(page.prev)) %>">
        <i class="icon icon-angle-right"></i>
    </a>
  </div>
<% } %>
```

其中`icon icon-angle-left`和`icon icon-angle-right`应该就是目前所用的样式，你可以修改为自己喜欢的。目前这个玩意好像有个bug导致文章末尾和这两个图标有重叠，需要在每篇文章末尾加上两个`<br>`才会显得比较美观。

我也是用户，并不是大佬😄

**Comment by forsigner** [comment]
@HeroadZ @ykqmain 暂时没太多时间更新这个主题，欢迎新想法，最好pr咯，我看到后会尽快merged
