### ISSUE TITLE
文章目录设置成 fixed 会不会更好 ?

### ISSUE THREAD

**Issue by scarletsky** [forsigner/fexo#13]
我发现文章目录只在文章顶部显示，如果把文章目录设置成 fixed，在文章内容较多的时候可以很方便的做到章节跳转。

**Comment by reverland** [comment]
+1 

现在回到顶部的方案觉得也行。。。

我是非常怀念next主题中会自行折叠展开的toc

**Comment by forsigner** [comment]
已fixed，已放弃 Pure CSS @scarletsky @reverland ,现在可以肆无忌惮的写JS了  555~

**Comment by scarletsky** [comment]
谢谢~

**Comment by reverland** [comment]
......
