### ISSUE TITLE
这个主题支持数学公式和mermaid吗？

### ISSUE THREAD

**Issue by daidai21** [forsigner/fexo#131]
谢谢你的主题，感觉很好，用了好久了才来道谢~~~
这个主题支持数学公式和mermaid吗？

**Comment by ykqmain** [comment]
> 使用 Mathjax
要使用 Mathjax，可以通过 Hexo 插件 [hexo-renderer-mathjax](https://github.com/phoenixcw/hexo-renderer-mathjax) 支持
查看 hexo-renderer-mathjax 文档


http://forsigner.com/2016/03/10/fexo-doc-zh-cn/#使用-Mathjax

**Comment by daidai21** [comment]
好的
