### ISSUE TITLE
如何自定义图标

### ISSUE THREAD

**Issue by esahcorp** [forsigner/fexo#133]
感谢作者和其他代码贡献者的奉献

请问怎么增加自定义的图标集呢，想在现有的基础上再增加一点图标？

我自己尝试了一下，在 style.css, style.css.map, fontello.svg 三个文件中做了一些修改，但是图标显示异常
![image](https://user-images.githubusercontent.com/14778381/46850991-89295080-ce28-11e8-8fea-d0612a05c10a.png)

请问这种问题怎么解决呢

**Comment by ykqmain** [comment]
先从这里下载相关资源 http://fontello.com

然后修改相关文件。

**Comment by esahcorp** [comment]
请问怎么修改文件？我在[另一个 issue](https://github.com/forsigner/fexo/issues/16#event-905361731) 看到相关问题，但老实说 css 不太熟，所以不知道怎么修改，有相关例子也行

**Comment by forsigner** [comment]
@esahcorp 暂时没提供直接配置自定义图标，你是要 instagram 图标？我晚点加进预置icon里去吧
