### ISSUE TITLE
layout.ejs报错

### ISSUE THREAD

**Issue by liamLacuna** [forsigner/fexo#136]
今天想更新blog 发现layout.ejs有报错

/Users/liam/Desktop/myBlog/themes/fexo/layout/layout.ejs:14
    12|
    13|   <% if (theme.post.showComments && page.layout === 'post'){ %>
 >> 14|     <%- partial('_partial/component/comments', {className: 'comments-post'}) %>
    15|   <% } else if (page.comments) { %>
    16|     <%- partial('_partial/component/comments', {className: 'comments-' + page.layout}) %>
    17|   <% } %>

/Users/liam/Desktop/myBlog/themes/fexo/layout/_partial/component/comments.ejs:8
    6|     <%- partial('hypercomments') %>
    7|     <%- partial('uyan') %>
 >> 8|     <%- partial('valine') %>
    9|   </div>
    10|

/Users/liam/Desktop/myBlog/themes/fexo/layout/_partial/component/valine.ejs:2
    1|
 >> 2| <% if (theme.valine.enable){ %>
    3|     <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
    4|     <script src="//unpkg.com/valine@latest/dist/Valine.min.js"></script>
    5|     <div id="comment" class="vcomment" ></div>

Cannot read property 'enable' of undefined

**Comment by forsigner** [comment]
fixed
