### ISSUE TITLE
关于博客评论系统

### ISSUE THREAD

**Issue by tai769** [forsigner/fexo#137]
看到你开通了gitalk但是不知道为什么我们的开通不了 只要把gtialk哪一行注释到改一些东西就行了嘛 但是有些不对 希望请你讲解一下

**Comment by forsigner** [comment]
更新一下 fexo 主题

**Comment by codevvvv9** [comment]
@forsigner  我就是最新版的，我试了两遍了依然不行

**Comment by forsigner** [comment]
给我看一下你的配置呗

**Comment by codevvvv9** [comment]
@forsigner  好的，我重新下载一遍，再试试

**Comment by codevvvv9** [comment]
@我看master分支是好几年前的更新啊，我即使又重新clone新的，好像和我第一次下载的没啥区别啊

**Comment by forsigner** [comment]
不是吧 最近都有更新啊

**Comment by codevvvv9** [comment]
@forsigner  确实是，不过只有_config.yml，7天前更新啊:smile:，又更新了一遍，可以评论了，太感谢啦～
