### ISSUE TITLE
显示"等待unpkg.com的响应"

### ISSUE THREAD

**Issue by xlindo** [forsigner/fexo#140]
valine 原有公共CDN的问题，找到`valine.ejs`编辑其内容换一个CDN，修改
`<script src="//unpkg.com/valine/dist/Valine.min.js"></script>`为
`<script src="//cdn.jsdelivr.net/npm/valine@latest/dist/Valine.min.js"></script>`

**Comment by forsigner** [comment]
恩 jsdelivr 比较靠谱
