### ISSUE TITLE
多行代码块一些问题

### ISSUE THREAD

**Issue by reverland** [forsigner/fexo#15]
1. 消除竖直滚动条。要不要对pre overflow-y: hidden? 我觉得水平的也可以不要，但需要能滚动
2. 代码背景颜色，只有有字的地方有颜色。。

![screenshot from 2016-03-08 20 48 03](https://cloud.githubusercontent.com/assets/1418726/13602125/b69afb08-e56f-11e5-8e84-1d473b1bf56c.png)

**Comment by forsigner** [comment]
水平还是要的，overflow-y: hidden 可以有，已改

**Comment by reverland** [comment]
谢谢，还有请教下更新是怎么更新。。。我每次一pull就把自己的配置覆盖了。。。

**Comment by forsigner** [comment]
你先commit一下，然后pull就好了
