### ISSUE TITLE
icon-mail图标字体

### ISSUE THREAD

**Issue by reverland** [forsigner/fexo#16]
![screenshot from 2016-03-08 21 01 47](https://cloud.githubusercontent.com/assets/1418726/13602359/3e2813d4-e571-11e5-8f90-5c8220a0b634.png)

**Comment by forsigner** [comment]
已加上，我暂时预制了下面这些常用的icon，迟点我写个文档怎么自定义icon

**Comment by ykqmain** [comment]
@forsigner  加个twitter就好了

**Comment by forsigner** [comment]
@reverland 好的

**Comment by forsigner** [comment]
icon-twitter 已加

**Comment by ykqmain** [comment]
@forsigner  好快😳
请 尽快解决 手机上 浏览文章 的问题，这是个大bug

**Comment by ykqmain** [comment]
@forsigner  怎么自定义icon？

**Comment by forsigner** [comment]
@ykqmain CSS 熟吗？在自定义CSS中自定义相关的class即可
