### ISSUE TITLE
目前的back to top太生硬

### ISSUE THREAD

**Issue by imbyron** [forsigner/fexo#17]
希望有一个加速的过程。
http://www.jq22.com/yanshi66
这个就挺好的。

**Comment by reverland** [comment]
+1，
而且并不想什么时候都出现

**Comment by imbyron** [comment]
@reverland 可以在配置哪里自定义的。

**Comment by forsigner** [comment]
@reverland @imbyron  之前一直不想引入JS，想Pure CSS，所以没做动画，现在bact top已经改善。

**Comment by imbyron** [comment]
@forsigner 改变浏览器尺寸后，比如占一半屏幕，这时候back top就不见了。

**Comment by reverland** [comment]
@forsigner 我不知道为什么更新后backtop消失了。。。

**Comment by forsigner** [comment]
@reverland 你再更新一下
