### ISSUE TITLE
数学公式显示

### ISSUE THREAD

**Issue by salvete** [forsigner/fexo#170]
我按照网上各种教程添加mathjax后，本地可以显示数学公式，但是github.io上面就是不显示。别人的都是next主题，这个主题关于数学显示方面几乎没有。。。

**Comment by stevenjoezhang** [comment]
可以安装插件： https://github.com/next-theme/hexo-filter-mathjax

**Comment by salvete** [comment]
> 可以安装插件： https://github.com/next-theme/hexo-filter-mathjax
可以了！谢谢你，感激不尽！祝你有愉快的一天~
