### ISSUE TITLE
如何开启搜索页面？

### ISSUE THREAD

**Issue by Besthulk** [forsigner/fexo#19]
用你这个主题，但是不知道搜索功能如何弄出来？麻烦具体指导说明一下，谢谢～

**Comment by EyreFree** [comment]
启用友链页面

在博客根目录执行 hexo new page search
修改my-blog/source/search/index.md里面的内容:
---
title: search
layout: search
comments: false
---




然后我就不知道了...QAQ

**Comment by Besthulk** [comment]
但是不是所想象的那样效果，我之前这样尝试过了。。

**Comment by forsigner** [comment]
@EyreFree @Besthulk 新做的功能，忘记更新文档了

## 启用搜索页面

- 在博客根目录执行 `hexo new page search`
- 修改`my-blog/source/search/index.md`里面的内容:

``` bash
---
title: search
layout: search
comments: false
---
```

- 然后安装 Hexo 插件 `hexo-search` (重要)

先进入 blog 的根目录

```bash
$ cd my-blog
$ npm install hexo-search --save
```

详见文档：[#启用搜索页面](http://forsigner.com/2016/03/10/fexo-doc-zh-cn/#启用搜索页面)

**Comment by Besthulk** [comment]
可以了，谢啦～

**Comment by EyreFree** [comment]
感谢，🙏

**Comment by MoeRookie** [comment]
您好，如何更改搜索入口？
我明明是本地搜索，也搜索到了内容，但搜索结果是直接进了另外一个地址路径；

**Comment by lone0x0** [comment]
> 您好，如何更改搜索入口？
> 我明明是本地搜索，也搜索到了内容，但搜索结果是直接进了另外一个地址路径；

我也是，请问解决了吗

**Comment by ddkk3000** [comment]
你的网站挂了，看不到了。搜索功能依照设置还是用不了

**Comment by lone0x0** [comment]
> 你的网站挂了，看不到了。搜索功能依照设置还是用不了

在config.yml添加路径即可

**Comment by lone0x0** [comment]
> 你的网站挂了，看不到了。搜索功能依照设置还是用不了
![截屏2022-05-26 13 14 43](https://user-images.githubusercontent.com/78702504/170420848-3ade0e82-56a8-42d1-9cc7-ae9cd975dc54.png)
在url那里改成你博客地址试试 我记得当时是这么解决的

**Comment by ddkk3000** [comment]
> > 你的网站挂了，看不到了。搜索功能依照设置还是用不了
> > ![截屏2022-05-26 13 14 43](https://user-images.githubusercontent.com/78702504/170420848-3ade0e82-56a8-42d1-9cc7-ae9cd975dc54.png)
> > 在 url 那里改成你博客地址试试 我记得当时是这么解决的

谢谢，设置好了。可以了。就是这里的问题。
