### ISSUE TITLE
为什么在本地跑着没事，挂在网上布局就乱了。

### ISSUE THREAD

**Issue by xcc3641** [forsigner/fexo#2]
http://imxie.cc
Bug就出现在“盒子“那里

**Comment by forsigner** [comment]
请问你什么时候 clone 的代码？ `hexo deploy` 之前有 执行 `hexo generate` 吗？

**Comment by xcc3641** [comment]
有的，我一般都是 hexo d -g 
就是今天重新更新了你的代码。现在换回原来的主题了。

**Comment by forsigner** [comment]
我明天在v2找你吧，这里不能实时聊天

**Comment by forsigner** [comment]
@xcc3641 我知道原因了，是因为我把_config.yml ignore 掉，用了_config.template.yml，现在已经用回_config.yml，你pull 一下代码应该就好了。

**Comment by xcc3641** [comment]
嗯嗯 好的，感谢感谢。

**Comment by forsigner** [comment]
@xcc3641  可以了吗？

**Comment by xcc3641** [comment]
我明天试试看，回寝室没有网。

**Comment by scarletsky** [comment]
你可以试试先执行一次 `hexo clean`，再 `hexo deploy --generate`。

**Comment by forsigner** [comment]
不再活跃的issue  关啦
