### ISSUE TITLE
css文件缺少

### ISSUE THREAD

**Issue by Jackroyal** [forsigner/fexo#20]
首先,非常感谢作者,挑了很久,最后选择了这款主题,非常感谢
使用过程中 发现几个问题,我现在部署的博客是[star](http://huirong.github.io)
<S>1. 然后抓包发现缺少`http://huirong.github.io/css/forsigner.css`这个文件,我去发布的目录看,确实没有这个css文件,不知道是什么问题,昨天刚pull的最新的代码</S>
2. 手机上,盒子在页面点击没有效果,但是一刷新页面,盒子就是打开状态,浏览器是小米自带浏览器和UC浏览器
额,1是我的问题,没仔细看文档
ps:我刚去作者你自己的博客看了下,为什么盒子点了 有时候不弹出来?这是本身的设定吗?

还有个小建议,`盒子`能做成可配置的吗?比如 我不想叫盒子两个字

**Comment by forsigner** [comment]
样式缺少已修复，我更新了文档，详情请看：[#个性化设置](http://forsigner.com/2016/03/10/fexo-doc-zh-cn/#个性化设置)

**Comment by forsigner** [comment]
@Jackroyal toolbox的文字也可以配置了，看文档里盒子的配置
