### ISSUE TITLE
关于邮箱的显示

### ISSUE THREAD

**Issue by time-river** [forsigner/fexo#23]
考虑到垃圾邮件问题，HTML代码中的邮箱能否用base64？

**Comment by forsigner** [comment]
@time-river 是指友链页面和关于页面吗？

**Comment by time-river** [comment]
是的。

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.3.8&pv=5.1&source=email_footer_2] On Mon, Apr 11, 2016 at 11:54 AM, forsigner < notifications@github.com [notifications@github.com] > wrote:
@time-river [https://github.com/time-river] 是指友链页面和关于页面吗？

**Comment by forsigner** [comment]
@time-river 邮箱是写在fexo/_config.yml里的，你直接写成base64就好了
