### ISSUE TITLE
非常看好和喜欢这个主题，能否增加一个高逼格的打赏功能（支付宝和微信）？

### ISSUE THREAD

**Issue by thinkhejie** [forsigner/fexo#26]
非常看好和喜欢这个主题，能否增加一个高逼格的打赏功能（支付宝和微信）？

**Comment by forsigner** [comment]
@thinkhejie 你希望怎样打赏功能呢？ 或者在那个页面？

**Comment by thinkhejie** [comment]
希望每篇文章的末尾能自动加上一个打赏按钮。点出来以后出现两个二维码，一个支付宝 一个微信。

**Comment by YangDejie** [comment]
同希望增加打赏功能

**Comment by forsigner** [comment]
@thinkhejie  @YangDejie 已支持，但是还需完善，暂时必须同时使用微信和支付宝

效果：

![](http://7xrn7f.com1.z0.glb.clouddn.com/16-6-23/77040607.jpg)

**Comment by YangDejie** [comment]
已经看到

**Comment by YangDejie** [comment]
已经看到，建议issue close【ps:  Forsigner 很帅】
