### ISSUE TITLE
选择drak主题，背景没有变化 

### ISSUE THREAD

**Issue by 07** [forsigner/fexo#30]

**Comment by forsigner** [comment]
背景颜色需要自己用CSS实现哦，不知你对CSS熟不熟

**Comment by forsigner** [comment]
# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

**Comment by yj3** [comment]
额，想要改成自己喜欢的，要花些时间，我就保持现在的算了，不过这主题还真不错，hexo所有的主题的用过，也搜索过一些其他的，也就2，3个自己喜欢的。哎，太挑剔了。

**Comment by forsigner** [comment]
可以自己改 或者自己搞一个 哈哈
