### ISSUE TITLE
'config page nav' in _config.yml

### ISSUE THREAD

**Issue by zerosrat** [forsigner/fexo#33]
Hi forsigner,

在 `page_nav` 里添加一个新的页面导航，如以下代码：

```
  - name: 读书阁
    url: /categories/Reading
    target_blank: false
```

进入读书阁，发现内容和分类内容是相同的。请问是我的设置有问题么（存在 `categories: Reading` 的post）

**Comment by forsigner** [comment]
你是想/categories/Reading这个url只显示Reading这个category的文章吗？

**Comment by zerosrat** [comment]
恩恩，对的~
