### ISSUE TITLE
关于after_footer.ejs

### ISSUE THREAD

**Issue by detectiveboy** [forsigner/fexo#34]
forsigner，你好！
我打算在我的博客中使用Mathjax，在网上查阅了资料说要在修改主题的after_footer.ejs，但是我在这个主题下没有找到after_footer.ejs这个文件。请问该如何解决？

**Comment by forsigner** [comment]
不需要改主题源码哦，直接用插件好了
详看文档：http://forsigner.com/2016/03/10/fexo-doc-zh-cn/#使用-Mathjax

**Comment by detectiveboy** [comment]
嗯，谢谢了。没有仔细看文档真是抱歉。
