### ISSUE TITLE
建议：增加订阅功能

### ISSUE THREAD

**Issue by thirtyyuan** [forsigner/fexo#40]
非常感谢你的fexo主题，超级喜欢！想请问下能不能增加订阅功能？方便发文章后通知订阅者。还有想请教下：多说评论在config.yml开启，并注释了Disqus 后，评论功能完全没有了，只使用Disqus 的话也经常加载不出来，有什么方法可以解决嘛？谢谢啦😁

**Comment by forsigner** [comment]
订阅功能已经有哦，在盒子里面的RSS

**Comment by forsigner** [comment]
评论不注释应该就可以显示啊 @thirtyyuan

**Comment by thirtyyuan** [comment]
好的，我再试试😄非常感谢！

**Comment by thirtyyuan** [comment]
多说评论已经启用，非常感谢😁想再麻烦你下，`_config.yml`里面盒子的RSS已经开启，但是`hexo s`，测试时，盒子的RSS里面显示`Cannot GET /atom.xml`，请问是还需要怎么配置吗？不好意思啊...

**Comment by forsigner** [comment]
@thirtyyuan 需安装hexo插件 `hexo-generator-feed`

**Comment by forsigner** [comment]
done
