### ISSUE TITLE
已经生成的标签不会消失

### ISSUE THREAD

**Issue by liangzr** [forsigner/fexo#41]
这个问题其实我不知道是不是主题的原因，还是 hexo 自己的，或者是其他的。  
  
比如我曾经用过一个叫 **_Linux_** 的标签，后来我又删除了文章，但这个标签依然还显示 **_Linux(0)_**，但数目是 0 

[link](http://blog.liangzr.me/tag/) 可以点进来看看

**Comment by geekbing** [comment]
遇到同样的问题

**Comment by YangDejie** [comment]
先hexo clean 然后再hexo d -g

**Comment by liangzr** [comment]
确实解决了，哈哈，只会傻瓜式的生成
