### ISSUE TITLE
一个移植的项目

### ISSUE THREAD

**Issue by Svtter** [forsigner/fexo#5]
你好，forsigner！

感谢您的优秀作品。

我根据您的此项目做了leanote笔记平台的移植，尚不清楚是否违反了MIT协议，希望得到您的许可。

项目地址如下：https://github.com/Svtter/fnote-theme

如果存在不足，或者侵犯了您的权益，我会尽快根据您的要求进行更改。

谢谢！

**Comment by forsigner** [comment]
欢迎  哈哈~
