### ISSUE TITLE
[bug] back top top 在 Safari 下报错

### ISSUE THREAD

**Issue by lilonghe** [forsigner/fexo#53]
我这边测试时报错，在你的网站上并没有报错，但是不能用！

调试后发现
scroll-spy.js
getItem 函数中

有以下代码：

```
var id = ary[i].hash.replace(/^#/, '');
var $target = document.getElementById(id);
```

在 Safari 下 id 是 decode 过的。Chrome正常，所以没去看
改成以下正确:

```
var id = decodeURI(ary[i].hash.replace(/^#/, ''));
var $target = document.getElementById(id);
```

原本想推 PR 的，但是想想好像不会哎~~~

**Comment by forsigner** [comment]
@lilonghe 欢迎PR  哈哈

**Comment by forsigner** [comment]
@lilonghe 要不你PR吧  弄一次就会了

**Comment by forsigner** [comment]
@lilonghe 你能把你文章组下面的支持一下贡献到 Fexo主题来吗? 你那个设计太酷了

就是这个：
![](http://forsigner.com/images/do.png)

**Comment by lilonghe** [comment]
@forsigner 看见右上角木有 就那个小猫
点它

**Comment by forsigner** [comment]
@lilonghe 哦哦 原来是开源的  那我把他整合到Fexo里去
