### ISSUE TITLE
轴线偏移不一致

### ISSUE THREAD

**Issue by ykqmain** [forsigner/fexo#65]
这个盒子里面有几个项目
![](http://ww2.sinaimg.cn/large/65e4f1e6gw1f9tv43gfhoj20vw0dydgu.jpg)

<br> <br> 

当处于这几个页面时，轴线是靠右的
![](http://ww3.sinaimg.cn/large/65e4f1e6gw1f9tv5328bcj20hu0cy74y.jpg)

<br> <br> 

当处于后面的几个页面时，轴线会偏左
![](http://ww1.sinaimg.cn/large/65e4f1e6gw1f9tv5yzgz4j20dw0a0weg.jpg)

<br> <br> 

当你处在 “标签”页，点击“友链”页，跳转后就感觉很明显了

![](http://ww2.sinaimg.cn/large/65e4f1e6gw1f9tvu5eh32g218g0ra14o.gif)

@forsigner

**Comment by forsigner** [comment]
@ykqmain 这都被你发现了

**Comment by forsigner** [comment]
fixed

**Comment by ykqmain** [comment]
@forsigner
其实我早就发现了，第一版就有这个问题，我也在其他问题里面提过，只是被你忽略了，困扰了我几个月了，真难受。
这几天我实在受不了了，就新开了一个问题→_→

**Comment by forsigner** [comment]
@ykqmain 已修复
