### ISSUE TITLE
搜索页面遇到的一些问题？

### ISSUE THREAD

**Issue by poetries** [forsigner/fexo#68]
1、本地执行后，hexo-search安装不了

```
$ cd my-blog
$ npm install hexo-search --save
```
出现以下问题
![11](https://cloud.githubusercontent.com/assets/16177576/20461420/bd6ed290-af38-11e6-9d78-4cefc2f82d6f.png)

2、在加入`travis-ci`后想保留原来的搜索功能，`hexo-search`这个插件如何加入,`travis-ci`得配置信息中 

![2](https://cloud.githubusercontent.com/assets/16177576/20461440/4fac88dc-af39-11e6-8f5f-d258bf5e78a6.png)

**Comment by forsigner** [comment]
@poetries 能不能截图安装`hexo-search`的报错截图，上面是warning

**Comment by poetries** [comment]
@forsigner  只有warning 没其他信息了

**Comment by forsigner** [comment]
@poetries 你的node和npm是什么版本？ 我找了windows测试没问题，而且`hexo-search`的依赖只有：

```json
"dependencies": {
    "utils-merge": "^1.0.0"
  }
```
你可以测试一下身边的其他电脑，看看有没有相同的问题

**Comment by poetries** [comment]
@forsigner ok 是我的问题
