### ISSUE TITLE
关于文章目录的建议

### ISSUE THREAD

**Issue by MaxineCaulfield** [forsigner/fexo#7]
文章页面的目录部分，要是文章过长想跳转到其他标题还需要拖动滚动条到最上面不是太方便。
建议更改或者添加个可选设置让目录列表固定，不会随着滚动条下拉而不见。

**Comment by forsigner** [comment]
恩恩 我晚点加个配置

**Comment by MaxineCaulfield** [comment]
感谢 :+1:  很棒的主题

**Comment by forsigner** [comment]
@MaxineCaulfield 文章目录体验以改善
