### ISSUE TITLE
[bug] 新增上/下一篇按钮后， 页面出现了两个滚动条

### ISSUE THREAD

**Issue by Keleir** [forsigner/fexo#71]
:exclamation: 我更新完代码后生效了， 但发现一个问题：**新增上/下一篇按钮后， 页面出现了两个滚动条**

## Before
![scroll_bar](https://cloud.githubusercontent.com/assets/7112075/21561125/7761e014-cea3-11e6-8222-a8a04b13f6b4.png)

## After
![scroll_bar_double](https://cloud.githubusercontent.com/assets/7112075/21561199/450ef4f2-cea4-11e6-85c6-42689eba798e.png)

> @forsigner  为啥我在 `themes/fexo/_config.yml` 的 post 下加了 `show_prev_next: true` ， 但没有生效呢:question:  :confused:

**Comment by forsigner** [comment]
@Keleir 修复了，你更新试试

**Comment by Keleir** [comment]
代码更新后 两个滚动条的问题修复了， 但上/下一篇按钮的显示效果不佳；

![image](https://cloud.githubusercontent.com/assets/7112075/21792524/66949f8a-d725-11e6-9d42-4cf86789b68c.png)


> @Keleir 修复了，你更新试试
