### ISSUE TITLE
搜索功能问题

### ISSUE THREAD

**Issue by xiaobinhong1** [forsigner/fexo#77]
输入关键字，结果有css样式相关代码输出，不应该这么干吧？

**Comment by forsigner** [comment]
@xiaobinhong1 现在搜索不是很智能，直接文字匹配的

**Comment by learninton** [comment]
bundle.js?235683:1 GET http://blog.learninto.top/search.json 404 (Not Found)

我的搜索报这个错是为什么？
Blog URL：[http://blog.learninto.top/search/](http://blog.learninto.top/search/)

**Comment by forsigner** [comment]
你的插件没配置好
https://github.com/forsigner/hexo-search
