### ISSUE TITLE
首页问题和关于字体问题

### ISSUE THREAD

**Issue by ghost** [forsigner/fexo#8]
我想顶级域名显示home_nav，然后点blog进入子目录，该怎么配置呢？
目前我是放在blog子目录下，用的post。
还有关于页面的字体是不是有点太大了，我chrome看的比较大，firefox看着还可以。style.css找了半天没找到在哪里改

**Comment by forsigner** [comment]
修改样式要修改sass文件，把gulp起起来就好了

**Comment by forsigner** [comment]
求pull request 哈
