### ISSUE TITLE
project页面index.md是空白的，修改不了是怎么回事儿啊？

### ISSUE THREAD

**Issue by helloqingfeng** [forsigner/fexo#80]
我看了下，我的source文件夹下的project、about、link之类的文件夹里的index.md都为空了，不知道到是怎么弄得。网页显示的还是我以前设置的内容。
后来我在index.md里面添加了内容，然后hexo clean、hexo g、hexo d之后，网站页面上还是以前的内容，没有改变，请问如何解决？

**Comment by lcnju** [comment]
我的也是空的，比如about这样的页面，只有有那个开始的一点就行，比如这样
https://github.com/lcnju/blog/blob/master/source/about/index.md

about，project，about，link这些内容是在配置里设置后自动生成的，并不是手动打入的
想要修改他们需要在配置文件`_config.yml`里改，像这样
https://github.com/lcnju/blog/blob/master/themes/fexo/_config.yml#L121-L137

最后的效果如下
https://www.lcorange.cn/about/

**Comment by helloqingfeng** [comment]
原来是在那里改啊，我还以为是在index.md文件下修改呢。看来是搞忘记了。谢谢啦！

**Comment by helloqingfeng** [comment]
已经解决好了，欢迎访问。http://helloqingfeng.github.io/project/
