### ISSUE TITLE
能否加入背景

### ISSUE THREAD

**Issue by Stephen-Chen** [forsigner/fexo#9]
我认为原来的博客布局似乎有太多的空白（首页尤其明显）是否能够加入背景的功能？
我个人比较喜欢淡颜色的背景，谢谢

**Comment by forsigner** [comment]
可以啊，我在_config.yml 加个配置哈

**Comment by Stephen-Chen** [comment]
@forsigner 多谢，要不是我不会Sass,现在就不用麻烦别人了

**Comment by Stephen-Chen** [comment]
@forsigner 看最近更新较多,是否考虑加入这个功能

**Comment by forsigner** [comment]
@Stephen-Chen 这家天有点忙，其实这个功能已经做好，我晚上更新一下文档哈

**Comment by forsigner** [comment]
@Stephen-Chen 背景图片可以配置了，[#文档传送门](http://forsigner.com/2016/03/10/fexo-doc-zh-cn/#个性化设置)

可以实现以下效果：

![1](http://i.imgur.com/YA9bXA8.jpg)
![2](http://i.imgur.com/D1NpeLt.jpg)
![3](http://i.imgur.com/fVSnfIC.jpg)

**Comment by Stephen-Chen** [comment]
Thanks
