### ISSUE TITLE
无法打开demo和文档页面

### ISSUE THREAD

**Issue by Asleepludan** [forsigner/fexo#99]
很喜欢这个主题，但是无法打开demo和文档的页面。

**Comment by ChaBug** [comment]
翻墙就可以了

**Comment by sherryriver** [comment]
@Asleepludan  作者的域名应该失效了 可以访问他原始github域名 http://forsigner.github.io/

**Comment by Asleepludan** [comment]
@sherryriver 谢谢，可以访问了
